---
sidebar: sidebar 
permalink: concept-before-you-begin-to-deploy-gfc.html 
keywords: global file cache, core, edge, management server 
summary: 开始在云中和远程办公室部署BlueXP边缘缓存之前、您需要了解许多要求。 
---
= 在开始部署BlueXP边缘缓存之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
开始在云中和远程办公室部署BlueXP边缘缓存之前、您需要了解许多要求。



== BlueXP边缘缓存核心设计注意事项

根据您的要求、您可能需要部署一个或多个BlueXP边缘缓存核心实例来创建BlueXP边缘缓存网络结构。Core实例用于引导分布式BlueXP边缘缓存边缘实例与数据中心文件服务器资源(例如文件共享、文件夹和文件)之间的流量。

在设计BlueXP边缘缓存部署时、您需要确定在可扩展性、资源可用性和冗余方面适合您环境的内容。BlueXP边缘缓存核心可通过以下方式部署：

* 独立实例
* 负载分布式设计(冷备用)


请参见 <<规模估算准则>> 要了解每个配置可以支持的最大 Edge 实例数和用户总数，请执行以下操作：

请咨询NetApp解决方案工程师、了解最适合企业部署的选项。



== 规模估算准则

在配置初始系统时，您需要牢记一些规模估算准则比率。在累积了一些使用历史记录之后，您应重新访问这些比率，以确保以最佳方式使用系统。其中包括：

* 边线/模芯比率
* 分布式用户/边缘比率
* 分布式用户/核心比率




=== 每个核心实例的边缘实例数

我们的准则建议每个BlueXP边缘缓存核心实例最多包含10个边缘实例、每个BlueXP边缘缓存核心实例最多包含20个边缘。这在很大程度上取决于最常见工作负载的类型和平均文件大小。在某些情况下、对于比较常见的工作负载、您可以为每个核心添加更多的边缘实例、但在这种情况下、您应联系您的客户代表、确定如何根据文件集的类型和大小正确调整边缘和核心实例的数量。


NOTE: 您可以同时利用多个BlueXP边缘缓存边缘和核心实例、根据需求横向扩展基础架构。



=== 每个 Edge 实例的并发用户数

BlueXP Edge缓存边缘可处理缓存算法和文件级差分方面的繁重工作。一个边缘实例可以为每个专用_physicic性_边缘实例提供多达500个用户、而为专用_virtual_部署提供多达300个用户。这在很大程度上取决于最常见工作负载的类型和平均文件大小。对于较大的协作文件类型、请根据物理或虚拟部署、确定每个BlueXP Edge缓存边缘下边界的最大用户数的50%。对于平均文件大小小于1 MB的更常见Office项目、请参考每个边缘的100%用户上限(具体取决于物理或虚拟部署)。


NOTE: BlueXP边缘缓存边缘可检测它是在虚拟实例上运行还是在物理实例上运行、它会将与本地虚拟文件共享的SMB连接数限制为最多300或500个并发连接。



=== 每个核心实例的并发用户数

BlueXP边缘缓存核心实例具有极高的可扩展性、建议每个核心使用3、000个并发用户。这在很大程度上取决于最常见工作负载的类型和平均文件大小。

请咨询NetApp解决方案工程师、了解最适合企业部署的选项。



== 前提条件

本节所述的前提条件适用于云中安装的组件：BlueXP边缘缓存管理服务器和BlueXP边缘缓存核心。

有关BlueXP边缘缓存边缘前提条件的说明、请参见以下链接：download-gFC-res풴.html#bluexp-edge caching边缘缓存要求[此处]。



=== 存储平台（卷）

后端存储平台(在本示例中为您部署的Cloud Volumes ONTAP 实例)应显示SMB文件共享。要通过BlueXP边缘缓存公开的任何共享都必须在共享级别允许"Everyone (任何人)"组完全控制、同时通过NTFS权限限制权限。

如果尚未在 Cloud Volumes ONTAP 实例上至少设置一个 SMB 文件共享，则需要准备好以下信息，以便可以在安装期间配置此信息：

* Active Directory 域名，名称服务器 IP 地址， Active Directory 管理员凭据。
* 要创建的卷的名称和大小，要创建卷的聚合的名称以及共享名称。


建议卷的大小足以容纳应用程序的总数据集，并能够随着数据集的增长相应地进行扩展。如果工作环境中有多个聚合，请参见 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-aggregates.html["管理现有聚合"^] 确定哪个聚合可为新卷提供最多的可用空间。



=== BlueXP边缘缓存管理服务器

BlueXP边缘缓存管理服务器需要通过HTTPS进行外部访问(TCP端口443)、以连接到云提供商订阅服务并访问以下URL：

* https://gfcproxyforcm-prod.azurewebsites.net/
* https://rest.zuora.com/v1/subscriptions/
* https://rest.zuora.com/oauth/token
* https://talonazuremicroservices.azurewebsites.net
* https://talonlicensing.table.core.windows.net


要使BlueXP边缘缓存软件正常运行、必须将此端口排除在任何WAN优化设备或防火墙限制策略之外。

BlueXP边缘缓存管理服务器还需要实例的唯一(地理) NetBIOS名称(例如GFC-MS1)。


NOTE: 一个管理服务器可支持在不同工作环境中部署的多个BlueXP边缘缓存核心实例。从BlueXP部署时、每个工作环境都有自己单独的后端存储、并且不包含相同的数据。



=== BlueXP边缘缓存核心

BlueXP边缘缓存核心侦听TCP端口范围6618-6630。根据您的防火墙或网络安全组（ Network Security Group ， NSG ）配置，您可能需要明确允许通过入站端口规则访问这些端口。此外、要使BlueXP边缘缓存软件正常运行、必须将这些端口排除在任何WAN优化设备或防火墙限制策略之外。

BlueXP边缘缓存核心要求如下：

* 实例的唯一（地理） NetBIOS 名称（例如， GFC-Core1 ）
* Active Directory domain name
+
** 实例应加入Active Directory域。
** 实例应在BlueXP边缘缓存特定组织单位(OU)中进行管理、并从继承的公司GPO中排除。


* 服务帐户。Core上的服务以特定域用户帐户的身份运行。此帐户(也称为服务帐户)必须在要与BlueXP边缘缓存核心实例关联的每个SMB服务器上具有以下权限：
+
** 配置的服务帐户必须是域用户。
+
根据网络环境中的限制级别和 GPO ，此帐户可能需要域管理员权限。

** 它必须具有 " 运行即服务 " 权限。
** 密码应设置为 " 永不过期 " 。
** 应禁用（未选中）帐户选项 " 用户必须在下次登录时更改密码 " 。
** 它必须是后端文件服务器内置备份操作员组的成员(通过BlueXP部署时会自动启用此功能)。






=== 许可证管理服务器

* BlueXP边缘缓存许可证管理服务器(LMS)应配置在Microsoft Windows Server 2016标准版或数据中心版或Windows Server 2019标准版或数据中心版上、最好配置在数据中心或云中的BlueXP边缘缓存核心实例上。
* 如果您需要单独的BlueXP边缘缓存LMS实例、则需要在原始Microsoft Windows Server实例上安装最新的BlueXP边缘缓存软件安装包。
* LMS实例需要能够使用HTTPS (TCP端口443)连接到订阅服务(公有 Internet)。
* 核心和边缘实例需要使用 HTTPS （ TCP 端口 443 ）连接到 LMS 实例。




=== 网络（外部访问）

BlueXP边缘缓存LMS需要通过HTTPS (TCP端口443)对以下URL进行外部访问。

* 如果您使用的是基于 GFC 订阅的许可：
+
** https://rest.zuora.com/v1/subscriptions/<subscription-no>
** https://rest.zuora.com/oauth/token


* 如果您使用的是基于 NetApp NSS 的许可：
+
** https://login.netapp.com
** https://login.netapp.com/ms_oauth/oauth2/endpoints
** https://login.netapp.com/ms_oauth/oauth2/endpoints/oauthservice/tokens


* 如果您使用的是基于 NetApp 传统的许可：
+
** https://talonazuremicroservices.azurewebsites.net
** https://talonlicensing.table.core.windows.net






=== 网络

* 防火墙：BlueXP边缘缓存边缘和核心实例之间应允许TCP端口。
* BlueXP边缘缓存TCP端口：443 (HTTPS)、6618-6630。
* 必须将网络优化设备(例如Riverbed Steelhead)配置为直通BlueXP边缘缓存专用端口(TCP 6618-6630)。

