---
sidebar: sidebar 
permalink: download-gfc-resources.html 
keywords: global file cache, edge 
summary: 开始在远程办公室安装BlueXP Edge缓存边缘软件之前、您需要了解许多要求。 
---
= 开始部署BlueXP边缘缓存边缘实例之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
开始在远程办公室安装BlueXP Edge缓存边缘软件之前、您需要了解许多要求。



== 下载所需资源

下载计划在分支机构中使用的BlueXP边缘缓存虚拟模板、软件安装包和其他参考文档：

* Windows Server 2016 虚拟模板：
+
https://repo.cloudsync.netapp.com/gfc/2k16-2.1.zip["包括 NetApp GFC （ VMware vSphere 6.5 及更高版本）的 Windows Server 2016 .OVA"^]
https://repo.cloudsync.netapp.com/gfc/2k16_GFC_2_2_0_41IMAGE.zip["包括 NetApp GFC （ Microsoft Hyper-V ）的 Windows Server 2016 .vhdx"^]

* Windows Server 2019 虚拟模板：
+
https://repo.cloudsync.netapp.com/gfc/2k19-2.1.zip["包括 NetApp GFC （ VMware vSphere 6.5 及更高版本）的 Windows Server 2019 .OVA"^]
https://repo.cloudsync.netapp.com/gfc/2k19_GFC_2_2_0_41IMAGE.zip["包括 NetApp GFC （ Microsoft Hyper-V ）的 Windows Server 2019 .vhdx"^]

* BlueXP Edge缓存边缘软件：
+
https://repo.cloudsync.netapp.com/gfc/GFC-2-2-0-41-Release.exe["NetApp GFC 软件安装包（ .exe ）"^]

* 适用于Cloud Insights 的全局文件缓存信息板：
+
https://repo.cloudsync.netapp.com/gfc/ci-gfc-dashboards.zip["NetApp GFC Cloud Insights 信息板(.ZIP)"]

* 全局文件缓存文档：
+
https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.2.0%20User%20Guide.pdf["《 NetApp 全局文件缓存用户指南》（ .PDF ）"^]



链接：Task－Deploy－gFC-edge－instances．html#update-bluexp-edge caching－edge－softsoftware [按照以下步骤]升级BlueXP Edge缓存软件。


NOTE: 在Windows Server 2016上部署BlueXP边缘缓存时、应使用.NET Framework 4.8和Windows WebView2 Framework。



== 设计和部署BlueXP Edge缓存边缘

根据您的要求、您可能需要根据分支机构中的并发用户会话部署一个或多个边缘实例。边缘实例向分支机构内的最终用户提供虚拟文件共享、该共享已从关联的BlueXP边缘缓存核心实例透明扩展。BlueXP边缘缓存边缘应包含 `D:\` NTFS卷、其中包含分支机构内的缓存文件。


NOTE: 对于BlueXP Edge缓存边缘、了解非常重要 link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["规模估算准则"]。这将有助于您为BlueXP边缘缓存部署制定正确的设计。您还需要确定在规模、资源可用性和冗余方面哪些适合您的环境。



=== BlueXP边缘缓存边缘实例

在部署BlueXP边缘缓存边缘实例时、您需要通过部署Windows Server 2016 Standard或Datacenter Edition、Windows Server 2019 Standard或Datacenter Edition或使用边缘缓存来配置单个VM `.OVA` 或 `.VHD` 模板、其中包括所选的Windows Server操作系统和BlueXP边缘缓存软件。



==== 快速步骤

. 部署BlueXP边缘缓存虚拟模板、Windows Server 2016虚拟机或Windows Server 2019 Standard或Datacenter版本。
. 确保虚拟机已连接到网络，已加入域并可通过 RDP 访问。
. 安装最新的BlueXP Edge缓存Edge软件。
. 确定BlueXP边缘缓存管理服务器和核心实例。
. 配置BlueXP边缘缓存边缘实例。




== BlueXP Edge缓存边缘要求

BlueXP边缘缓存边缘可在支持Windows Server 2016和2019的所有平台上运行、为企业远程办公室及其他地方简化了IT。至关重要的是、只要满足一些基本级别的要求、几乎在所有情况下都可以在现有硬件基础架构、虚拟化或混合/公共云环境中部署BlueXP边缘缓存。

要使Edge以最佳状态运行、需要以下硬件和软件资源。有关整体规模估算准则的详细信息，请参见 link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["规模估算准则"]。



=== 经过加固的服务器设备

BlueXP边缘缓存安装包可在任何Microsoft Windows Server实例上创建一个强化软件设备。_不卸载_ BlueXP边缘缓存包。卸载BlueXP边缘缓存将影响服务器实例的功能、并且可能需要完全重建服务器实例。



=== 物理硬件要求

* 至少 4 个 CPU 核
* 至少 16 GB RAM
* 专用单个或冗余 1 Gbps NIC
* 10K RPM SAS HDD 或 SSD （首选）
* 启用了回写缓存功能的 RAID 控制器




=== 虚拟部署要求

从存储子系统的角度来看，虚拟机管理程序平台的性能可能会下降（例如延迟）。为了使用BlueXP边缘缓存获得最佳性能、建议使用具有SSD的物理服务器实例。

为了在虚拟环境中获得最佳性能，除了物理主机要求之外，还必须满足以下要求和资源预留：

Microsoft Hyper-V 2012 R2 及更高版本：

* 处理器（ CPU ）： CPU 必须设置为 * 静态 * ：最小： 4 个 vCPU 核心。
* 内存（ RAM ）：最小： 16 GB 设置为 * 静态 * 。
* 硬盘配置：硬盘必须配置为 * 固定磁盘 * 。


VMware vSphere 6.x 及更高版本：

* 处理器（ CPU ）：必须设置 CPU 周期预留。最小值： 4 个 vCPU 核心 @ 10000 MHz 。
* Memory （ RAM ）：最小：预留 16 GB 。
* 硬盘配置：
+
** 磁盘配置必须设置为 * 厚配置主动置零 * 。
** 硬盘共享必须设置为 * 高 * 。
** 必须使用vSphere Client将devices.hotplug设置为*False，以防止Microsoft Windows将BlueXP边缘缓存驱动器显示为可移动驱动器。


* 网络连接：必须将网络接口设置为 * 。 VMXNET3* （可能需要 VM 工具）。


Edge在Windows Server 2016和2019上运行、因此虚拟化平台需要支持操作系统、并与可提高VM子操作系统性能和VM管理(如VM Tools)的实用程序集成。



=== 分区规模估算要求

* C ： \ - 最小 250 GB （系统 / 启动卷）
* D ： \ - 最小 1 TB （用于全局文件缓存智能文件缓存的单独数据卷 * ）


* 最小大小是活动数据集的 2 倍。缓存卷（ D ： \ ）可以扩展，并且仅受 Microsoft Windows NTFS 文件系统限制。



=== 全局文件缓存智能文件缓存磁盘要求

全局文件缓存智能文件缓存磁盘（ D ： \ ）上的磁盘延迟应为每个并发用户提供小于 0.5 毫秒的平均 I/O 磁盘延迟和 1 MiBps 吞吐量。

有关详细信息，请参见 https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.2.0%20User%20Guide.pdf["《 NetApp 全局文件缓存用户指南》"^]。



=== 网络

* 防火墙：应允许在BlueXP边缘缓存边缘和管理服务器与核心实例之间使用TCP端口。
+
BlueXP边缘缓存TCP端口：443 (HTTPS - LMS)、6618 - 6630。

* 必须将网络优化设备(例如Riverbed Steelhead)配置为直通BlueXP边缘缓存专用端口(TCP 6618-6630)。




=== 客户端工作站和应用程序最佳实践

BlueXP边缘缓存透明地集成到客户环境中、允许用户使用运行企业级应用程序的客户端工作站访问集中式数据。使用BlueXP边缘缓存、数据可通过直接驱动器映射或DFS命名空间进行访问。有关BlueXP边缘缓存网络结构、智能文件缓存和软件关键方面的详细信息、请参阅 link:concept-before-you-begin-to-deploy-gfc.html["在开始部署BlueXP边缘缓存之前"^] 部分。

为了确保获得最佳体验和性能，请务必遵循《全局文件缓存用户指南》中所述的 Microsoft Windows 客户端要求和最佳实践。此适用场景适用于所有版本的 Microsoft Windows 。

有关详细信息，请参见 https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.2.0%20User%20Guide.pdf["《 NetApp 全局文件缓存用户指南》"^]。



=== 防火墙和防病毒最佳实践

虽然BlueXP边缘缓存会尽力验证最常见的防病毒应用程序套件是否与全局文件缓存兼容、但NetApp无法保证也不对这些程序或其关联更新、Service Pack或修改导致的任何不兼容性或性能问题负责。

NetApp建议不要在任何启用了BlueXP边缘缓存的实例(Core或Edge)上安装或应用监控或防病毒解决方案。如果是根据选择或策略安装解决方案，则必须应用以下最佳实践和建议。有关常见防病毒套件，请参见中的附录 A https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.2.0%20User%20Guide.pdf["《 NetApp 全局文件缓存用户指南》"^]。



=== 防火墙设置

* Microsoft 防火墙：
+
** 保留默认防火墙设置。
** 建议：对于标准BlueXP边缘缓存边缘实例、将Microsoft防火墙设置和服务保留为默认设置Off、而不启动。
** 建议：将 Microsoft 防火墙设置和服务保留为默认设置 on ，并为同时运行域控制器角色的 Edge 实例启动。


* 企业防火墙：
+
** BlueXP边缘缓存核心实例侦听TCP端口6618-6630、确保BlueXP边缘缓存边缘实例可以连接到这些TCP端口。
** BlueXP边缘缓存实例需要通过TCP端口443 (HTTPS)与BlueXP边缘缓存管理服务器进行通信。


* 必须将网络优化解决方案/设备配置为直通BlueXP边缘缓存专用端口。




=== 防病毒最佳实践

NetApp已经测试了最常用的防病毒产品、包括Cylance、McAfee、Symantec、Sophos、Trend Micro、 Kaspersky、人群攻击、Cisco AMP、Tannium和Windows Defender、与BlueXP边缘缓存结合使用。防病毒软件应通过NetApp认证、只有在配置了正确的排除列表后才受支持。请参见中的附录A https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.2.0%20User%20Guide.pdf["《 NetApp 全局文件缓存用户指南》"^]


NOTE: 向Edge设备添加防病毒软件可能会对用户性能产生10-20%的影响。

有关详细信息，请参见 https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.2.0%20User%20Guide.pdf["《 NetApp 全局文件缓存用户指南》"^]。



==== 配置排除项

防病毒软件或其他第三方索引编制或扫描实用程序绝不能扫描 Edge 实例上的驱动器 D ： \ 。这些对 Edge 服务器驱动器 D ： \ 的扫描将导致对整个缓存命名空间发出大量文件打开请求。这将导致通过 WAN 将文件提取到数据中心优化的所有文件服务器。Edge 实例上会发生 WAN 连接泛洪和不必要的负载，从而导致性能下降。

除了D：\驱动器之外、通常应从所有防病毒应用程序中排除以下BlueXP边缘缓存目录和进程：

* `C ： \Program Files\TalonFAST\`
* `C ： \Program Files\TalonFAST\Bin\LMClientService.exe`
* `C ： \Program Files\TalonFAST\Bin\LMServerService.exe`
* `C ： \Program Files\TalonFAST\Bin\Optimus.exe`
* `C ： \Program Files\TalonFAST\Bin\tafsexport.exe`
* `C ： \Program Files\TalonFAST\Bin\tafsutils.exe`
* `C ： \Program Files\TalonFAST\Bin\tapp.exe`
* `C ： \Program Files\TalonFAST\Bin\TappN.exe`
* `C ： \Program Files\TalonFAST\Bin\FTLSummaryGenerate.exe`
* C：\Program Files\TalonFAST\Bin\GfcCIAgentService.exe
* `C ： \Program Files\TalonFAST\Bin\RFASTSetupWizard.exe`
* `C ： \Program Files\TalonFAST\Bin\TService.exe`
* `C ： \Program Files\TalonFAST\Bin\tm.exe`
* `C ： \Program Files\TalonFAST\Fast调试 日志 \`
* `C ： \Windows\System32\drivers\tfast.sys`
* ` \\ ？ TafsMtPt ： \` 或 ` \ ？ TafsMtP*`
* ` \Device\TalonCachFS\`
* ` \\ ？ \GLOBALROOT\Device\TalonCachFS\`
* ` \\ ？ \GLOBALROOT\Device\TalonCachFS\*`




== NetApp 支持策略

BlueXP边缘缓存实例专门设计为在Windows Server 2016和2019平台上运行的主应用程序。BlueXP边缘缓存需要优先访问平台资源、例如磁盘、内存、网络接口、 并且可能会对这些资源提出很高的要求。虚拟部署需要预留内存 /CPU 和高性能磁盘。

* 对于分支机构部署、运行BlueXP边缘缓存的服务器上支持的服务和应用程序仅限于：
+
** DNS/DHCP
** Active Directory域控制器(BlueXP边缘缓存必须位于单独的卷上)
** 打印服务
** Microsoft System Center Configuration Manager （ Microsoft System Center Configuration Manager ， SCCM" ）
** BlueXP边缘缓存批准的客户端系统代理和防病毒应用程序


* NetApp支持和维护仅适用于BlueXP边缘缓存。
* 业务部门生产效率软件，通常需要大量资源，例如数据库服务器，邮件服务器等。 不支持。
* 客户负责运行BlueXP边缘缓存的服务器上可能安装的任何非BlueXP边缘缓存软件：
+
** 如果任何第三方软件包导致软件或资源与BlueXP边缘缓存发生冲突或性能受到影响、NetApp支持组织可能会要求客户禁用该软件或从运行BlueXP边缘缓存的服务器中删除该软件。
** 客户负责安装、集成、支持和升级添加到运行BlueXP边缘缓存应用程序的服务器中的任何软件。


* 防病毒工具和许可代理等系统管理实用程序 / 代理可能可以共存。但是、除了上面列出的受支持服务和应用程序之外、BlueXP边缘缓存不支持这些应用程序、仍需遵循上述准则：
+
** 客户负责安装、集成、支持和升级所添加的任何软件。
** 如果客户安装的任何第三方软件包导致或怀疑导致与BlueXP边缘缓存的软件或资源冲突、或者性能受到影响、BlueXP边缘缓存的支持组织可能会要求禁用/删除该软件。



